name: Deploy gh-pages to VPS


on:
  push:
    branches:
      - gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages

      - name: Deploy to VPS via rsync
        uses: burnett01/rsync-deployments@v2.0.0
        with:
          switches: -avzr --delete
          path: ./
          remote_path: /var/www/mssprt.site/
          remote_host: ${{ secrets.VPS_HOST }}
          remote_user: deploy
          remote_key: ${{ secrets.VPS_SSH_KEY }}
